[General]
upload_max_filesize = 200M
post_max_size = 220M

[Logging]
log_errors = On
display_errors = Off
display_startup_errors = Off


[PHPUnit]
error_reporting=-1
zend.assertions=1
assert.exception=1
memory_limit=-1
;extension=mbstring

[xdebug-3.0]
xdebug.mode=develop,debug,coverage
;xdebug.client_host=docker.sandbox.net
;xdebug.client_port=9000
;xdebug.idekey=vscode
;xdebug.start_with_request=yes
;xdebug.start_with_request=trigger
;xdebug.trigger_value=vscode