<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-22 at 11:20:14.
 */
class ContactusServiceTest extends TestCase {

    /**
     * @var ContactusServices
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new ContactusService();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers ContactusServices::contactUs
     * @todo   Implement testcontactUs().
     */
    public function testcontactUs() {
        
        $restResponse = new RestResponse();
        $reqObj = array(
            "firstName" => "Brijesh K.",
            "name" => "Brijesh Dhaker",
            "email" => "brijeshdhaker@gmail.com",
            "phone" => "+919820937445",
            "session_type"=> "Maternity",
            "message" => "test message",
            "rTyp" => "src",
            "uTyp" => "site",
        );
        
        $this->object->contactUs($reqObj, $restResponse);
        $this->assertTrue($restResponse->getStatus());
        
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
        
    }
}
