<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

use \RegistrationService;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-23 at 02:40:18.
 */
class RegistrationServiceTest extends TestCase {

    /**
     * @var RegistrationService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new RegistrationService();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers RegistrationService::register
     * @todo   Implement testregister().
     */
    public function testregister() {
        
        $this->assertEquals('', $this->object->register());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
        
    }
}
