<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-22 at 11:19:55.
 */
class SubscribeServiceTest extends TestCase {

    /**
     * @var SubscribeServices
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new SubscribeService();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers SubscribeServices::forNewletter
     * @todo   Implement testforNewletter().
     */
    public function testforNewletter() {
        
        $restResponse = new RestResponse();
        $reqObj = array(
            "name" => "Brijesh Dhaker",
            "email" => "brijeshdhaker@gmail.com",
            "interest_type" => "kids",
            "phone" => "+919820937445",
            "interest_type" => "Portraits",
            "message" => "I am interested for Portraits photography newsletter.",
            "rTyp" => "src",
            "uTyp" => "site",
        );
        
        $this->object->forNewletter($reqObj, $restResponse);
        $this->assertTrue($restResponse->getStatus());
        
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }
    
}
