<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-22 at 11:19:55.
 */
class SubscribeServiceTest extends TestCase {

    /**
     * @var SubscribeServices
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new SubscribeServices();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers SubscribeServices::forNewletter
     * @todo   Implement testforNewletter().
     */
    public function testforNewletter() {
        
        $restResponse = new RestResponse();
        $reqObj = array(
            "firstName" => "Brijesh K.",
            "name" => "Brijesh Dhaker",
            "email" => "brijeshdhaker@gmail.com",
            "phone" => "+919820937445",
            "message" => "test message",
            "rTyp" => "src",
            "uTyp" => "site",
        );
        $this->assertEquals('', $this->object->forNewletter($reqObj, $restResponse));
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers SubscribeServices::forCollaboration
     * @todo   Implement testforCollaboration().
     */
    public function testforCollaboration() {
        
        $restResponse = new RestResponse();
        $reqObj = array(
            "firstName" => "Brijesh K.",
            "name" => "Brijesh Dhaker",
            "email" => "brijeshdhaker@gmail.com",
            "phone" => "+919820937445",
            "message" => "test message",
            "rTyp" => "src",
            "uTyp" => "site",
        );
        
        $this->assertEquals('', $this->object->forCollaboration($reqObj, $restResponse));
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers SubscribeServices::forWorkWithUs
     * @todo   Implement testforWorkWithUs().
     */
    public function testforWorkWithUs() {
        
        $restResponse = new RestResponse();
        $reqObj = array(
            "firstName" => "Brijesh K.",
            "name" => "Brijesh Dhaker",
            "email" => "brijeshdhaker@gmail.com",
            "phone" => "+919820937445",
            "message" => "test message",
            "rTyp" => "src",
            "uTyp" => "site",
        );        
        $this->assertEquals('', $this->object->forWorkWithUs($reqObj, $restResponse));
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }
}
