<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

use \BookingService;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-23 at 03:09:58.
 */
class BookingServiceTest extends TestCase {

    /**
     * @var BookingService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new BookingService();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers BookingService::contactUs
     * @todo   Implement testcontactUs().
     */
    public function testPhotoSession() {
        
        $this->assertEquals('', $this->object->photoSession());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
