<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-22 at 11:20:14.
 */
class ContactusServiceTest extends TestCase {

    /**
     * @var ContactusServices
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new ContactusServices();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers ContactusServices::contactUs
     * @todo   Implement testcontactUs().
     */
    public function testcontactUs() {
        
        $this->assertEquals('', $this->object->contactUs());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
        
    }
}
