<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-13 at 09:47:37.
 */
class MappingHelperTest extends TestCase {

    /**
     * @covers MappingHelper::getMapping
     * @todo   Implement testGetMapping().
     */
    public function testGetMapping() {
        //$this->markTestIncomplete('This test has not been implemented yet.');
        $mapping = array(
            "ID" => "id",
            "CODE" => "code",
            "NAME" => "name",
            "GROUPS" => "group",
            "GNAME" => "groupName"
        );
        
        
        $this->assertSame($mapping, MappingHelper::getMapping('core-data'));
    }

}
