<?php declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-11 at 02:30:15.
 */


final class MailHelperTest extends TestCase {

    /**
     * @var MailHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp() : void {
        $this->object = new MailHelper;
        
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown() : void {
        
    }

    /**
     * @covers MailHelper::send
     * @todo   Implement testSend().
     */
    public function testSend(): void {
        
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
        $config = new NotificationConfig("neetastudio.in");
        
        $this->object = new Notification();
        $this->object->setTo("brijeshdhaker@gmail.com");
        $this->object->setFrom("photoes@neetastudio.in","Neeta Studio Photography");
        $this->object->setReplyTo("photoes@neetastudio.in","Neeta Studio Photography");
        $this->object->setSubject("Hello");
        $this->object->setBody("This is Test Main Message");
        $this->object->setFooter("This is Test Footer Message");
        $this->object->setCc("brijeshdhaker.it@gmail.com");
            
        MailHelper::send($emailObj, $config);
        
        $this->assertSame(true, true);
        
    }

}
