<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

//
#require('phpmail/PHPMailerAutoload.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-11 at 03:11:04.
 */
class NotificationTest extends TestCase {

    /**
     * @var Notification
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp() : void {
                
        $this->object = new Notification();
        $this->object->setTo("brijeshdhaker@gmail.com");
        $this->object->setFrom("photoes@neetastudio.in","Neeta Studio Photography");
        $this->object->setReplyTo("photoes@neetastudio.in","Neeta Studio Photography");
        $this->object->setSubject("Hello");
        $this->object->setBody("This is Test Main Message");
        $this->object->setFooter("This is Test Footer Message");
        $this->object->setCc("brijeshdhaker.it@gmail.com");
        
        //$this->object =  Notification::getNotifyObject($to, $subject, $body);
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown() : void {
        
    }

    /**
     * @covers Notification::getNotifyObject
     * @todo   Implement testGetNotifyObject().
     */
    public function testGetNotifyObject() {
        
        $to = "brijeshdhaker@gmail.com";
        $subject= "Hello";
        $body = "Test Message";
        $notification =  Notification::getNotifyObject($to, $subject, $body);
        $this->assertNotNull($notification);
        
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getToRecipients
     * @todo   Implement testGetToRecipients().
     */
    public function testGetToRecipients() {
        
        $toRecipients = array("brijeshdhaker@gmail.com");
        $this->assertEquals($toRecipients, $this->object->getToRecipients());
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getCcRecipients
     * @todo   Implement testGetCcRecipients().
     */
    public function testGetCcRecipients() {
        
        $ccRecipients = array("brijeshdhaker.it@gmail.com");
        $this->assertSame($ccRecipients, $this->object->getCcRecipients());
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getBCCRecipients
     * @todo   Implement testGetBCCRecipients().
     */
    public function testGetBCCRecipients() {
        
        $this->assertNull($this->object->getBCCRecipients());
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getTo
     * @todo   Implement testGetTo().
     */
    public function testGetTo() {
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setTo
     * @todo   Implement testSetTo().
     */
    public function testSetTo() {
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getCc
     * @todo   Implement testGetCc().
     */
    public function testGetCc() {
        
        $this->assertSame("brijeshdhaker.it@gmail.com", $this->object->getCc());
        // Remove the following lines when you implement this test.
        // $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setCc
     * @todo   Implement testSetCc().
     */
    public function testSetCc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getBcc
     * @todo   Implement testGetBcc().
     */
    public function testGetBcc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setBcc
     * @todo   Implement testSetBcc().
     */
    public function testSetBcc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getSubject
     * @todo   Implement testGetSubject().
     */
    public function testGetSubject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getEmailMessage
     * @todo   Implement testGetEmailMessage().
     */
    public function testGetEmailMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setMessage
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getBody
     * @todo   Implement testGetBody().
     */
    public function testGetBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setBody
     * @todo   Implement testSetBody().
     */
    public function testSetBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Notification::getFooter
     * @todo   Implement testGetFooter().
     */
    public function testGetFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setFooter
     * @todo   Implement testSetFooter().
     */
    public function testSetFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Notification::getAttachments
     * @todo   Implement testGetAttachments().
     */
    public function testGetAttachments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setAttachment
     * @todo   Implement testSetAttachment().
     */
    public function testSetAttachment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Notification::getData
     * @todo   Implement testGetData().
     */
    public function testGetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getFrom
     * @todo   Implement testGetFrom().
     */
    public function testGetFrom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setFrom
     * @todo   Implement testSetFrom().
     */
    public function testSetFrom() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::getReplyTo
     * @todo   Implement testGetReplyTo().
     */
    public function testGetReplyTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Notification::setReplyTo
     * @todo   Implement testSetReplyTo().
     */
    public function testSetReplyTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
