<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-22 at 15:07:26.
 */
class OnclickEnvTest extends TestCase {

    /**
     * @var OnclickEnv
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new OnclickEnv();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers OnclickEnv::getEnvName
     * @todo   Implement testgetEnvName().
     */
    public function testgetEnvName() {
    
        $env = $this->object->getEnvName();
        $this->assertEquals('TEST', $env);
    
    }

    /**
     * @covers OnclickEnv::isWebRequest
     * @todo   Implement testisWebRequest().
     */
    public function testisWebRequest() {

        $isWebRequest = $this->object->isWebRequest();
        $this->assertEquals(false, $isWebRequest);
        
    }

    /**
     * @covers OnclickEnv::getAppName
     * @todo   Implement testgetAppName().
     */
    public function testgetAppName() {
        
        $app_name = $this->object->getAppName();    
        $this->assertEquals("neetastudio.in", $app_name);
    
    }

    /**
     * @covers OnclickEnv::getRepositoryPath
     * @todo   Implement testgetRepositoryPath().
     */
    public function testgetRepositoryPath() {

        $repopath = $this->object->getRepositoryPath();
        $this->assertEquals('/export/repository/TEST/', $repopath);
    
    }

    /**
     * @covers OnclickEnv::getDomain
     * @todo   Implement testgetDomain().
     */
    public function testgetDomain() {
        $domain = $this->object->getDomain();
        $this->assertEquals('neetastudio.in', $domain);

    }

    /**
     * @covers OnclickEnv::getRepoDomain
     * @todo   Implement testgetRepoDomain().
     */
    public function testgetRepoDomain() {

        $this->assertEquals('http://neetastudio.in', $this->object->getRepoDomain());

    }

    /**
     * @covers OnclickEnv::getFtpHotInfo
     * @todo   Implement testgetFtpHotInfo().
     */
    public function testgetFtpHotInfo() {
        //$this->assertEquals('', $this->object->getFtpHotInfo());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::serverProperties
     * @todo   Implement testserverProperties().
     */
    public function testserverProperties() {
        //$this->assertEquals('', $this->object->serverProperties());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }
}
