<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-22 at 15:07:26.
 */
class OnclickEnvTest extends TestCase {

    /**
     * @var OnclickEnv
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    #[\Override]
    protected function setUp(): void {
        $this->object = new OnclickEnv();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    #[\Override]
    protected function tearDown(): void {
        
    }

    /**
     * @covers OnclickEnv::getEnvName
     * @todo   Implement testgetEnvName().
     */
    public function testgetEnvName() {
        $this->assertEquals('DEV', $this->object->getEnvName());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::isWebRequest
     * @todo   Implement testisWebRequest().
     */
    public function testisWebRequest() {
        $this->assertEquals(false, $this->object->isWebRequest());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::getAppName
     * @todo   Implement testgetAppName().
     */
    public function testgetAppName() {
        $this->assertEquals('ONLINE', $this->object->getAppName());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::getRepositoryPath
     * @todo   Implement testgetRepositoryPath().
     */
    public function testgetRepositoryPath() {
        $this->assertEquals('/export/repository/DEV/', $this->object->getRepositoryPath());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::getDomain
     * @todo   Implement testgetDomain().
     */
    public function testgetDomain() {
        $this->assertEquals('http://neetastudio.in', $this->object->getDomain());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::getRepoDomain
     * @todo   Implement testgetRepoDomain().
     */
    public function testgetRepoDomain() {
        $this->assertEquals('http://neetastudio.in', $this->object->getRepoDomain());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::getFtpHotInfo
     * @todo   Implement testgetFtpHotInfo().
     */
    public function testgetFtpHotInfo() {
        //$this->assertEquals('', $this->object->getFtpHotInfo());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers OnclickEnv::serverProperties
     * @todo   Implement testserverProperties().
     */
    public function testserverProperties() {
        //$this->assertEquals('', $this->object->serverProperties());
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
    }
}
