<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-11 at 02:30:15.
 */


class MailHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MailHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MailHelper;
        
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MailHelper::send
     * @todo   Implement testSend().
     */
    public function testSend() {
        
        // Remove the following lines when you implement this test.
        //$this->markTestIncomplete('This test has not been implemented yet.');
        $config = new NotificationConfig("creativelights.in");
        
        $emailObj = new Notification();
        $emailObj->setTo("brijeshdhaker@gmail.com");
        $emailObj->setFrom("photoes@creativelights.in","Creative Lights Photography");
        $emailObj->setReplyTo("photoes@creativelights.in","Creative Lights Photography");
        $emailObj->setSubject("Hello");
        $emailObj->setBody("This is Test Main Message");
        $emailObj->setFooter("This is Test Footer Message");
        $emailObj->setCc("brijeshdhaker.it@gmail.com");
            
        MailHelper::send($emailObj, $config);
        
    }

}
